name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

jobs:
  build:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore rust compilation cache
        uses: Swatinem/rust-cache@v2
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Check cargo clippy warnings
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
